# Generated by Django 3.0.7 on 2020-06-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200624_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='console',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='game',
        ),
    ]
